name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ Run pytest
    - name: Run tests
      run: python -m pytest
      working-directory: ${{ github.workspace }}

    # 5️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t patient-booking-app .

    # 6️⃣ Login to Docker Hub (only on main branch)
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 7️⃣ Push Docker image
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag patient-booking-app ${{ secrets.DOCKERHUB_USERNAME }}/patient-booking-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/patient-booking-app:latest
